### ISSUE TITLE
Add a .cfignore file

### ISSUE THREAD

**Issue by seabaylea** [strongloop/loopback-example-bluemix#4]
There should also be a .cfignore file so that we don't push un-necessary files to CloudFoundry (usually the same as the .gitignore).

**Comment by hacksparrow** [comment]
The sample app by Bethany and Gibson has a more complete set of required files. I am also following the insightful discussions on the project.

This project will be updated accordingly.

**Comment by hacksparrow** [comment]
@seabaylea added https://github.com/strongloop/loopback-example-bluemix/blob/master/.cfignore
