### ISSUE TITLE
Add auto-scaling agent by default for Bluemix usecases

### ISSUE THREAD

**Issue by seabaylea** [strongloop/loopback-example-bluemix#5]
If we're creating a Bluemix app, we should add the Bluemix autoscaling agent (the auto-scaling service is free).

Bethany Griggs might have the sample code for that already.

**Comment by hacksparrow** [comment]
Noted.

**Comment by hacksparrow** [comment]
@raymondfeng undoing this default involves editing the `server.js` and `package.json` files. What is your suggestion? I am not very comfortable having it on by default in this example app. Examples should be as simple and as stripped down as possible to avoid confusion.

@chrisbygrave the `lb` generator has enabling auto-scaling agent as a default `Y`. I think that should suffice.

**Comment by hacksparrow** [comment]
> the lb generator has enabling auto-scaling agent as a default Y
